--------------------------------------------------------
--  File created - Wednesday-December-28-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AS_MERCHANT_ASSET
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."AS_MERCHANT_ASSET" 
   (	"MERCHANT_ASSET_ID" NUMBER, 
	"MERCHANT_ID" NUMBER, 
	"ASSET_TYPE" VARCHAR2(20 BYTE), 
	"ASSET_VALUE" NUMBER, 
	"OWNERSHIP_PERCENTAGE" FLOAT(126), 
	"POSSESSION_SINCE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AS_RISK_MANAGEMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."AS_RISK_MANAGEMENT" 
   (	"MERCHANT_RISK_DETAIL_ID" NUMBER, 
	"CREDIT_SCORE" NUMBER, 
	"KYC_SCORE" NUMBER, 
	"MIN_SUGGESTED_ENTITLEMENT" NUMBER, 
	"MAX_SUGGESTED_ENTITLEMENT" NUMBER, 
	"LIGITATION_INDEX_SCORE" NUMBER, 
	"COMPANY_REG_NO" NUMBER, 
	"FINANCE_INDICATOR_ID" VARCHAR2(20 BYTE), 
	"CREDIT_APP_HISTORY" VARCHAR2(20 BYTE), 
	"CCRIS" VARCHAR2(20 BYTE), 
	"BOUNDED_CHECK" VARCHAR2(20 BYTE), 
	"SSM" VARCHAR2(20 BYTE), 
	"BOARD_OF_DIRECTOR" VARCHAR2(200 BYTE), 
	"SHAREHOLDERS" VARCHAR2(200 BYTE), 
	"FINANCIAL_ANNUM_REPORT" VARCHAR2(20 BYTE), 
	"BUSINESS" VARCHAR2(20 BYTE), 
	"OFFICE_ADDRESS" VARCHAR2(30 BYTE), 
	"LGL" VARCHAR2(20 BYTE), 
	"PENDING_CASES" VARCHAR2(200 BYTE), 
	"CASES_HISTORY" VARCHAR2(200 BYTE), 
	"AMLA" VARCHAR2(20 BYTE), 
	"TR" VARCHAR2(200 BYTE), 
	"INVOICE_PAYMENT_PERFORMANCE" NUMBER, 
	"MERCHANT_ID" NUMBER, 
	"CREDIT_AGENT_ID" NUMBER, 
	"AGENT_NAME" VARCHAR2(20 BYTE), 
	"MERCHANT_RISK_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AS_MERCHANT_LIABILITY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."AS_MERCHANT_LIABILITY" 
   (	"MERCHANT_LIABILITY_ID" NUMBER, 
	"MERCHANT_ID" NUMBER, 
	"LIABILITY_OUTSTANDING" NUMBER, 
	"LIABILITY_TYPE" VARCHAR2(20 BYTE), 
	"LOAN_DATE" DATE, 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AS_MERCHANT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."AS_MERCHANT" 
   (	"MERCHANT_ID" NUMBER, 
	"MERCHANT_NAME" VARCHAR2(20 BYTE), 
	"SSM" VARCHAR2(20 BYTE), 
	"AWS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."AS_MERCHANT"."AWS" IS 'AVERAGE WEEKLY SALES';
REM INSERTING into SYSTEM.AS_MERCHANT_ASSET
SET DEFINE OFF;
REM INSERTING into SYSTEM.AS_RISK_MANAGEMENT
SET DEFINE OFF;
REM INSERTING into SYSTEM.AS_MERCHANT_LIABILITY
SET DEFINE OFF;
REM INSERTING into SYSTEM.AS_MERCHANT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index AS_MERCHANT_ASSET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."AS_MERCHANT_ASSET_PK" ON "SYSTEM"."AS_MERCHANT_ASSET" ("MERCHANT_ASSET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AS_RISK_MANAGEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."AS_RISK_MANAGEMENT_PK" ON "SYSTEM"."AS_RISK_MANAGEMENT" ("MERCHANT_RISK_DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AS_MERCHANT_LIABILITY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."AS_MERCHANT_LIABILITY_PK" ON "SYSTEM"."AS_MERCHANT_LIABILITY" ("MERCHANT_LIABILITY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AS_MERCHANT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."AS_MERCHANT_PK" ON "SYSTEM"."AS_MERCHANT" ("MERCHANT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AS_MERCHANT_ASSET
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AS_MERCHANT_ASSET" MODIFY ("MERCHANT_ASSET_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT_ASSET" MODIFY ("MERCHANT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT_ASSET" MODIFY ("ASSET_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT_ASSET" MODIFY ("ASSET_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT_ASSET" MODIFY ("OWNERSHIP_PERCENTAGE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT_ASSET" MODIFY ("POSSESSION_SINCE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT_ASSET" ADD CONSTRAINT "AS_MERCHANT_ASSET_PK" PRIMARY KEY ("MERCHANT_ASSET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AS_RISK_MANAGEMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("MERCHANT_RISK_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("CREDIT_SCORE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("KYC_SCORE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("MIN_SUGGESTED_ENTITLEMENT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("MAX_SUGGESTED_ENTITLEMENT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("LIGITATION_INDEX_SCORE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("COMPANY_REG_NO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("FINANCE_INDICATOR_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("CREDIT_APP_HISTORY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("CCRIS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("BOUNDED_CHECK" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("SSM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("BOARD_OF_DIRECTOR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("SHAREHOLDERS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("FINANCIAL_ANNUM_REPORT" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("BUSINESS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("OFFICE_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("LGL" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("PENDING_CASES" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("CASES_HISTORY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("AMLA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("TR" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("INVOICE_PAYMENT_PERFORMANCE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("MERCHANT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("CREDIT_AGENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("AGENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" MODIFY ("MERCHANT_RISK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" ADD CONSTRAINT "AS_RISK_MANAGEMENT_PK" PRIMARY KEY ("MERCHANT_RISK_DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AS_MERCHANT_LIABILITY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AS_MERCHANT_LIABILITY" MODIFY ("MERCHANT_LIABILITY_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT_LIABILITY" MODIFY ("MERCHANT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT_LIABILITY" MODIFY ("LIABILITY_OUTSTANDING" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT_LIABILITY" MODIFY ("LIABILITY_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT_LIABILITY" MODIFY ("LOAN_DATE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT_LIABILITY" MODIFY ("VALID_FROM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT_LIABILITY" MODIFY ("VALID_TO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT_LIABILITY" ADD CONSTRAINT "AS_MERCHANT_LIABILITY_PK" PRIMARY KEY ("MERCHANT_LIABILITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AS_MERCHANT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AS_MERCHANT" MODIFY ("MERCHANT_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT" MODIFY ("MERCHANT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT" MODIFY ("SSM" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT" MODIFY ("AWS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."AS_MERCHANT" ADD CONSTRAINT "AS_MERCHANT_PK" PRIMARY KEY ("MERCHANT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AS_MERCHANT_ASSET
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AS_MERCHANT_ASSET" ADD CONSTRAINT "ASSET_MERCHANT_FK4" FOREIGN KEY ("MERCHANT_ID")
	  REFERENCES "SYSTEM"."AS_MERCHANT" ("MERCHANT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AS_RISK_MANAGEMENT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" ADD CONSTRAINT "MERCHANT_RISK_ID_FK1" FOREIGN KEY ("MERCHANT_RISK_ID")
	  REFERENCES "SYSTEM"."AS_RISK_ENGINE" ("MERCHANT_RISK_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SYSTEM"."AS_RISK_MANAGEMENT" ADD CONSTRAINT "RM_MERCHANT_ID_FK1" FOREIGN KEY ("MERCHANT_ID")
	  REFERENCES "SYSTEM"."AS_MERCHANT" ("MERCHANT_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AS_MERCHANT_LIABILITY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."AS_MERCHANT_LIABILITY" ADD CONSTRAINT "MERCHANT_ID_FK3" FOREIGN KEY ("MERCHANT_ID")
	  REFERENCES "SYSTEM"."AS_MERCHANT" ("MERCHANT_ID") ENABLE;
