-- 11) A table named Account is created and it’s attributes are displayed.

CREATE TABLE AS_ACCOUNT
   (ACCOUNT_ID NUMBER PRIMARY KEY
            USING INDEX (CREATE INDEX AS_ACCOUNT_PK ON    
            AS_ACCOUNT(ACCOUNT_ID)), 
    ACCOUNT_NAME VARCHAR2(20 BYTE) NOT NULL, 
    DISTRICT_ID NUMBER NOT NULL, 
    DATE_CREATED DATE NOT NULL, 
    CUSTOMER_ID NUMBER, 
    MERCHANT_ID NUMBER,
    CONSTRAINT CUSTOMER_FK2 FOREIGN KEY (CUSTOMER_ID)
        REFERENCES AS_CUSTOMER (CUSTOMER_ID),
    CONSTRAINT DISTRICT_FK1 FOREIGN KEY (DISTRICT_ID)
        REFERENCES AS_DISTRICT (DISTRICT_ID),
    CONSTRAINT MERCHANT_FK6 FOREIGN KEY (MERCHANT_ID)
        REFERENCES AS_MERCHANT (MERCHANT_ID)
);

Insert into AS_ACCOUNT (ACCOUNT_ID,ACCOUNT_NAME,DISTRICT_ID,DATE_CREATED,CUSTOMER_ID,MERCHANT_ID) values (9,'A',1,to_date('28/12/2022','DD/MM/RRRR'),null,9);
Insert into AS_ACCOUNT (ACCOUNT_ID,ACCOUNT_NAME,DISTRICT_ID,DATE_CREATED,CUSTOMER_ID,MERCHANT_ID) values (10,'B',1,to_date('28/12/2022','DD/MM/RRRR'),null,10);
Insert into AS_ACCOUNT (ACCOUNT_ID,ACCOUNT_NAME,DISTRICT_ID,DATE_CREATED,CUSTOMER_ID,MERCHANT_ID) values (11,'C',1,to_date('28/12/2022','DD/MM/RRRR'),null,11);
Insert into AS_ACCOUNT (ACCOUNT_ID,ACCOUNT_NAME,DISTRICT_ID,DATE_CREATED,CUSTOMER_ID,MERCHANT_ID) values (12,'D',2,to_date('28/12/2022','DD/MM/RRRR'),null,12);

-- 12) The problem is when creating AS_ACOUNT, I have forgotten to store the password. So, I add a password column, with 65 characters for SHA256 encryption which is unique, while making ACCOUNT_NAME unique. The AS_Account table is altered by adding the attribute named ACCOUNT_PASSWORD. The before and after outputs are displayed below.

ALTER TABLE AS_ACCOUNT 
ADD (ACCOUNT_PASSWORD VARCHAR2(65) NOT NULL);

ALTER TABLE AS_ACCOUNT
ADD CONSTRAINT AS_ACCOUNT_UK1 UNIQUE 
(
  ACCOUNT_NAME, 
  ACCOUNT_PASSWORD
)
ENABLE;

COMMENT ON COLUMN AS_ACCOUNT.ACCOUNT_PASSWORD IS 'SHA256 encrypted';

